#!/usr/bin/env python3
"""
Alerting system for Zenith-Sentry.
Provides email alerts and notification capabilities.
"""
import smtplib
import logging
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from typing import List, Optional, Dict, Any
from dataclasses import dataclass
from datetime import datetime

logger = logging.getLogger(__name__)

@dataclass
class Alert:
    """Alert data class."""
    severity: str
    title: str
    message: str
    finding_id: Optional[str] = None
    scan_id: Optional[str] = None
    timestamp: Optional[datetime] = None
    metadata: Optional[Dict[str, Any]] = None

class EmailAlertSender:
    """Email alert sender for security alerts."""
    
    def __init__(
        self,
        smtp_host: str = "localhost",
        smtp_port: int = 587,
        smtp_username: Optional[str] = None,
        smtp_password: Optional[str] = None,
        use_tls: bool = True,
        from_email: str = "zenith-sentry@example.com"
    ):
        """
        Initialize email alert sender.
        
        Args:
            smtp_host: SMTP server host
            smtp_port: SMTP server port
            smtp_username: SMTP username
            smtp_password: SMTP password
            use_tls: Whether to use TLS
            from_email: From email address
        """
        self.smtp_host = smtp_host
        self.smtp_port = smtp_port
        self.smtp_username = smtp_username
        self.smtp_password = smtp_password
        self.use_tls = use_tls
        self.from_email = from_email
    
    def send_alert(
        self,
        to_emails: List[str],
        alert: Alert,
        subject: Optional[str] = None
    ) -> bool:
        """
        Send an alert email.
        
        Args:
            to_emails: List of recipient email addresses
            alert: Alert to send
            subject: Optional custom subject
            
        Returns:
            True if email sent successfully, False otherwise
        """
        try:
                            
            msg = MIMEMultipart()
            msg['From'] = self.from_email
            msg['To'] = ', '.join(to_emails)
            
            if subject:
                msg['Subject'] = subject
            else:
                msg['Subject'] = f"[Zenith-Sentry] {alert.severity.upper()}: {alert.title}"
            
            body = f"""
            <html>
            <body>
                <h2>Security Alert: {alert.title}</h2>
                <p><strong>Severity:</strong> {alert.severity}</p>
                <p><strong>Timestamp:</strong> {alert.timestamp or datetime.utcnow()}</p>
                <p><strong>Message:</strong></p>
                <p>{alert.message}</p>
                
                {self._format_metadata(alert.metadata) if alert.metadata else ''}
                
                <hr>
                <p><em>This alert was generated by Zenith-Sentry EDR.</em></p>
            </body>
            </html>
            """
            
            msg.attach(MIMEText(body, 'html'))
            
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                if self.use_tls:
                    server.starttls()
                
                if self.smtp_username and self.smtp_password:
                    server.login(self.smtp_username, self.smtp_password)
                
                server.send_message(msg)
            
            logger.info(f"Alert email sent to {len(to_emails)} recipients")
            return True
            
        except Exception as e:
            logger.error(f"Failed to send alert email: {e}")
            return False
    
    def _format_metadata(self, metadata: Dict[str, Any]) -> str:
        """Format metadata for email body."""
        if not metadata:
            return ""
        
        html = "<p><strong>Additional Information:</strong></p><ul>"
        for key, value in metadata.items():
            html += f"<li><strong>{key}:</strong> {value}</li>"
        html += "</ul>"
        return html

class AlertManager:
    """Manages alert rules and notifications."""
    
    def __init__(self, email_sender: Optional[EmailAlertSender] = None):
        """
        Initialize alert manager.
        
        Args:
            email_sender: EmailAlertSender instance
        """
        self.email_sender = email_sender
        self.alert_recipients: List[str] = []
        self.alert_rules: List[Dict[str, Any]] = []
    
    def add_recipient(self, email: str) -> None:
        """
        Add an alert recipient.
        
        Args:
            email: Email address to add
        """
        if email not in self.alert_recipients:
            self.alert_recipients.append(email)
            logger.info(f"Added alert recipient: {email}")
    
    def remove_recipient(self, email: str) -> None:
        """
        Remove an alert recipient.
        
        Args:
            email: Email address to remove
        """
        if email in self.alert_recipients:
            self.alert_recipients.remove(email)
            logger.info(f"Removed alert recipient: {email}")
    
    def add_alert_rule(
        self,
        name: str,
        condition: str,
        severity: str,
        enabled: bool = True
    ) -> None:
        """
        Add an alert rule.
        
        Args:
            name: Rule name
            condition: Alert condition (e.g., "risk_level == 'critical'")
            severity: Alert severity threshold
            enabled: Whether the rule is enabled
        """
        rule = {
            "name": name,
            "condition": condition,
            "severity": severity,
            "enabled": enabled
        }
        self.alert_rules.append(rule)
        logger.info(f"Added alert rule: {name}")
    
    def evaluate_alert(self, alert: Alert) -> bool:
        """
        Evaluate whether to send an alert based on rules.
        
        Args:
            alert: Alert to evaluate
            
        Returns:
            True if alert should be sent, False otherwise
        """
                                  
        severity_order = ["low", "medium", "high", "critical"]
        alert_severity_index = severity_order.index(alert.severity)
        
        for rule in self.alert_rules:
            if not rule["enabled"]:
                continue
            
            rule_severity_index = severity_order.index(rule["severity"])
            
            if alert_severity_index >= rule_severity_index:
                return True
        
        return alert.severity in ["high", "critical"]
    
    def send_alert(self, alert: Alert) -> bool:
        """
        Send an alert if it meets the criteria.
        
        Args:
            alert: Alert to send
            
        Returns:
            True if alert was sent, False otherwise
        """
        if not self.evaluate_alert(alert):
            logger.info(f"Alert did not meet criteria, not sending: {alert.title}")
            return False
        
        if not self.email_sender or not self.alert_recipients:
            logger.warning("No email sender or recipients configured, skipping alert")
            return False
        
        success = self.email_sender.send_alert(self.alert_recipients, alert)
        return success

_alert_manager: Optional[AlertManager] = None

def get_alert_manager() -> AlertManager:
    """Get the global alert manager instance."""
    global _alert_manager
    if _alert_manager is None:
        _alert_manager = AlertManager()
    return _alert_manager
